title: ARCHEON
description: Causal systems framework by Adam Karl Lucien

# GitHub Pages runtime address
url: "https://adamlucien.github.io"
baseurl: "/ARCHEON"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap